workflows:
  - app_dir: CiscoAI/kubeflow-workflows/test/workflows
    component: tf_mnist 
    name: e2e
  - app_dir: CiscoAI/kubeflow-workflows/test/workflows
    component: kubebench
    name: kb-e2e
